INSERT INTO models(name, modelCounts) VALUES ('Moria Goblins', 12),
('8 Elves and 4 Men of Gondor', 12),
('Frodo Baggins', 1),
('Uruk-hai', 10),
('Lurtz', 1),
('Aragorn', 1),
('Warriors of Rohan', 12),
('Legolas', 1),
('Uruk-hai Captain', 1),
('Uruk-hai', 10),
('Boromir', 1),
('Gandalf the Grey', 1),
('Horses', 6),
('Riders of Rohan', 6),
('Saruman', 1),
('Gandalf on Shadowfax', 1),
('Ugluk', 1),
('Grishnakh', 1),
('Mounted Eomer', 1),
('Gimli', 1),
('Moria Ruins', 1),
('Warriors of Minas Tirith', 12),
('Mordor Orcs', 12),
('Sam', 1),
('Faramir', 1),
('Seige Troop Spur', 1),
('Haldir', 1),
('Theoden', 1),
('Uruk-hai Beserker', 1),
('Seige Troop Spur', 1),
('Merry and Pippin', 2),
('Minas Tirith Banner Bearer', 1),
('Galadriel', 1),
('Elrond', 1),
('Witch King', 1),
('Grima Wormtongue', 1),
('Gandalf the White', 1),
('Royal Guard Mounted with Banner', 1),
('Mordor Orc Banner Bearer', 1),
('Mounted Faramir', 1),
('Gil-galad', 1),
('Elendil', 1),
('Isildur', 1),
('Aragorn on Brego', 1),
('Gorbag', 1),
('Shagrat', 1),
('Gamling', 1),
('Eowyn', 1),
('Hama', 1),
('Set of Plastic Ruins', 1),
('Minas Tirith Banner Bearer (Mounted)', 1),
('Gothmog on foot', 1),
('Denethor', 1),
('Orc Captain', 1),
('Faramir on Foot', 1),
('Boromir of Gondor (armoured)', 1),
('Aragorn (Strider)', 1),
('Bilbo', 1),
('Gollum', 1),
('Eomer', 1),
('Theodred', 1),
('Plastic Wargs', 6),
('Plastic Warg Riders', 6),
('Haradrim Warriors', 12),
('Haradrim sprue', 1),
('King of the Dead', 1),
('Mordor Orc sprue', 1),
('Merry and Pippin (Return of the King)', 1),
('Mounted Arwen with unconscious Frodo', 1),
('Witch king (Return of the King)', 1),
('Conversion kit', 1),
('Armoured Legolas (Return of the King)', 1),
('Easterling captain', 1),
('Aragorn Elessar', 1),
('Radagast the Brown', 1),
('Tom Bombadil', 1),
('Glorfindel', 1),
('Orc Shaman', 1),
('Dwarf Captain', 1),
('Durburz', 1),
('Balin', 1),
('Suladan', 1),
('Hasharin', 1),
('Imrahil', 1),
('Ghan-buri-Ghan', 1),
('Farmer Maggot and all three dogs', 4),
('Sharkey', 1);